monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_log
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        main_log:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug

        #log errors in error.log
        error_log:
            type: stream
            path: '%kernel.logs_dir%/error.log'
            level: error

        warnings_log:
            type: stream
            path: '%kernel.logs_dir%/warnings.log'
            level: warning

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!deprecation"]

